/*
 *  VieSched++ Very Long Baseline Interferometry (VLBI) Scheduling Software
 *  Copyright (C) 2018  Matthias Schartner
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file Model.h
 * @brief class Model
 *
 * @author Hank Lewis
 * @date 22.01.2026
 */

#ifndef MODEL_BASE_H
#define MODEL_BASE_H
#include <cassert>
#include <map>
#include <type_traits>

#ifdef WITH_GUROBI
#include <gurobi_c++.h>
#endif // WITH_GUROBI

#include "../Source/SourceList.h"
#include "../Station/Network.h"
#include "../Scan/Scan.h"

namespace VieVS {
// forward declaration for ModelCoverage
class ModelBase; 

/**
 * @class ModelCoverage
 * @brief abstract struct modelling sky coverage
 * @author Hank Lewis
 * @date 24.05.2025
 */
struct ModelCoverage {
    virtual size_t cellCount(void) const noexcept = 0;
    virtual size_t calculateCell(const ModelBase* model, size_t t, 
        const std::shared_ptr<const AbstractSource> q, Station& s) const noexcept = 0;
};

/**
 * @class ModelCoverage13
 * @brief derivation of ModelCoverage with 13 discrete regions
 * @author Hank Lewis
 * @date 24.05.2025
 */
struct ModelCoverage13 : public ModelCoverage {
    size_t cellCount(void) const noexcept final;
    size_t calculateCell(const ModelBase* model, size_t t, 
        const std::shared_ptr<const AbstractSource> q, Station& s) const noexcept final;
};

/**
 * @class Model
 * @brief wraps ILP implementation
 * @author Hank Lewis
 * @date 24.05.2025
 */
class ModelBase {
    friend struct ModelCoverage;
    friend struct ModelCoverage13;
public:
    /**
     * @brief constructor
     * @author Hank Lewis
     *
     * @param network network
     * @param sourceList sourceList
     * @param sourceMask sourceMask
     * @param blockLength blockLength
     * @param windowLength windowLength
     */
    ModelBase(VieVS::Network& network, VieVS::SourceList& sourceList, 
        const std::set<unsigned long>& sourceMask, 
        const std::shared_ptr<const ObservingMode>& modes,
        unsigned int blockLength, unsigned int windowLength);

    /**
     * @brief constructor with specified ModelCoverage implementation
     * @author Hank Lewis
     *
     * @param network network
     * @param sourceList sourceList
     * @param sourceMask sourceMask
     * @param blockLength blockLength
     * @param windowLength windowLength
     */
    template<typename T>
    ModelBase(VieVS::Network& network, VieVS::SourceList& sourceList, 
        const std::set<unsigned long>& sourceMask, 
        const std::shared_ptr<const ObservingMode>& modes,
        unsigned int blockLength, unsigned int windowLength) : 
        ModelBase(network, sourceList, sourceMask, modes, blockLength, windowLength) {
            static_assert(std::is_base_of<ModelCoverage, T>::value, "unreachable");
            coverage_ = std::make_unique<T>();
        }

    /**
     * @brief destructor
     * @author Hank Lewis
    */
    ~ModelBase() = default;

    /**
     * @brief perform ILP optimization from scratch, without a starting point
     * @author Hank Lewis
     */
    bool optimize(void);

    /**
     * @brief perform ILP optimization using the greedy solution as a starting point
     * @author Hank Lewis
     *
     * @param scans the scans generated by Scheduler::start
     */
    std::vector<Scan> optimize(std::vector<Scan>& scans);
protected:
    virtual void prepare(size_t tp, size_t t0, size_t tf, size_t tn) = 0;
protected:
    bool checkStationVisibility(size_t t, 
        std::shared_ptr<const VieVS::AbstractSource> q, 
        Station& s) const noexcept;

    bool checkBaselineViability(size_t t, 
        std::shared_ptr<const VieVS::AbstractSource> q, 
        const Baseline& b) noexcept;

    unsigned int calculateMinObsExact(unsigned int t,
        const std::shared_ptr<const AbstractSource>& q,
        const Baseline& b,
        const std::shared_ptr<const Mode> &mode);

    size_t calculateMinObs(size_t t,
        const std::shared_ptr<const AbstractSource>& q,
        const Baseline& b,
        const std::shared_ptr<const Mode> &mode);

    unsigned int calculateSlewTimeExact(Station& s, 
        const std::shared_ptr<const AbstractSource> q1, 
        const std::shared_ptr<const AbstractSource> q2,
        unsigned int t1, unsigned int t2) const noexcept;

    size_t calculateSlewTime(Station& s, 
        const std::shared_ptr<const AbstractSource> q1, 
        const std::shared_ptr<const AbstractSource> q2,
        size_t t1, size_t t2) const noexcept;
protected:
    // references from VieVS::Scheduler
    VieVS::Network& network_;
    VieVS::SourceList& sourceList_;
    std::set<unsigned long> sourceMask_;
    std::shared_ptr<const ObservingMode> modes_;
    std::unique_ptr<ModelCoverage> coverage_;
    // number of segments in schedule
    size_t blockCount_;
    // the size of each time segment (in seconds)
    unsigned int blockLength_;
    // number of optimization windows
    size_t windowCount_;
    // number of segments in each window
    size_t windowBlockCount_;
    // the length of the sliding optimization window (in seconds)
    unsigned int windowLength_;
protected:
    std::vector<size_t> getBlocks(size_t t0, size_t tf) const noexcept;
    std::vector<size_t> getBlocks(size_t t0, size_t tf, const std::shared_ptr<const AbstractSource>& q, Station& s) const noexcept;
    std::vector<size_t> getBlocks(size_t t0, size_t tf, const std::shared_ptr<const AbstractSource>& q, const Baseline& b) noexcept;
    std::vector<std::reference_wrapper<Station>> getStations() noexcept;
    std::vector<std::reference_wrapper<Station>> getStations(size_t t, const std::shared_ptr<const AbstractSource>& q) noexcept;
    std::vector<std::reference_wrapper<const Baseline>> getBaselines() const noexcept;
    std::vector<std::reference_wrapper<const Baseline>> getBaselines(size_t t, const std::shared_ptr<const AbstractSource>& q) noexcept;
    std::vector<std::shared_ptr<const AbstractSource>> getSources() const noexcept;
    std::vector<std::shared_ptr<const AbstractSource>> getSources(size_t t, Station& s) const noexcept;
    std::vector<std::shared_ptr<const AbstractSource>> getSources(size_t t, const Baseline& b) noexcept;
#ifdef WITH_GUROBI
protected:
    /**
    * @class ModelKey
    * @brief key for accessing ILP variables
    * @author Hank Lewis
    * @date 03.03.2026
    */
    struct ModelKey {
        enum ModelKeyType {
            sta_active,
            bln_active,
            sta_coverage
        };
        ModelKeyType type;
        union {
            struct { size_t q, s, t; } sta_active;
            struct { size_t q, b, t; } bln_active;
            struct { size_t s, c; } sta_coverage;
        } key;
        std::string name;

        bool operator<(const ModelKey& other) const;
        bool operator==(const ModelKey& other) const noexcept;

        struct Hash {
            size_t operator()(const ModelKey& k) const noexcept {
                size_t h = std::hash<int>{}(static_cast<int>(k.type));
                auto combine = [&](size_t v) {
                    h ^= std::hash<size_t>{}(v)
                    + 0x9e3779b97f4a7c15ULL
                    + (h << 6)
                    + (h >> 2);
                };
                switch(k.type) {
                case ModelKey::sta_active:
                    combine(k.key.sta_active.q);
                    combine(k.key.sta_active.s);
                    combine(k.key.sta_active.t);
                    break;
                case ModelKey::bln_active:
                    combine(k.key.bln_active.q);
                    combine(k.key.bln_active.b);
                    combine(k.key.bln_active.t);
                    break;
                case ModelKey::sta_coverage:
                    combine(k.key.sta_coverage.s);
                    combine(k.key.sta_coverage.c);
                    break;
                }
                return h;
            }
        };

        static ModelKey StaActive(const ModelBase* model, 
            std::shared_ptr<const VieVS::AbstractSource> const q, 
            const Station& s, size_t t);

        static ModelKey BlnActive(const ModelBase* model, 
            std::shared_ptr<const VieVS::AbstractSource> const q, 
            const Baseline& b, size_t t);

        static ModelKey StaCoverage(const ModelBase* model, const Station& s, size_t c);

        inline std::string getName() const noexcept { return name; }
    };
protected:
    boost::optional<GRBVar> getVar(const ModelKey& key) const noexcept;
    bool* getSol(const ModelKey& key) noexcept;
    const bool* getSol(const ModelKey& key) const noexcept;

    GRBVar& addVar(const ModelKey& key, double lb, double ub, double obj, char vtype);
    bool& addSol(const ModelKey& key);
protected:
    template<typename F>
    void apply(size_t t0, size_t tf, F op) {
        for(size_t t : ModelBase::getBlocks(t0, tf)) {
            for(const auto q : ModelBase::getSources()) {
                for(Station& s : ModelBase::getStations(t, q)) {
                    auto var = *getVar(ModelKey::StaActive(this, q, s, t));
                    op(var);
                }
            }
        }

        for(size_t t : ModelBase::getBlocks(t0, tf)) {
            for(const auto q : ModelBase::getSources()) {
                for(const Baseline& b : ModelBase::getBaselines(t, q)) {
                    auto var = *getVar(ModelKey::BlnActive(this, q, b, t));
                    op(var);
                }
            }
        }
    }
private:
    struct ScanBuilder {
        unsigned long qId;
        std::map<unsigned long, std::pair<PointingVector, size_t>> sData;
        std::set<unsigned long> sContinuation;

        // none indicates failure, true is a successful append, 
        // false indicates that a new scan needs to be created and this one terminated
        boost::optional<bool> append(const ModelBase* model, 
            std::shared_ptr<const VieVS::AbstractSource> const q, 
            Station& s, size_t t) noexcept;

        Scan finish(const ModelBase* model, 
            const std::vector<unsigned int>& slewTime, 
            std::vector<unsigned int>& endOfLastScan) const noexcept;
    };
private:
    class ActiveScans {
    private:
        std::vector<ScanBuilder> scans_;
        std::vector<ScanBuilder> scansToAppend_;
        const ModelBase* model_;
    public:
        ActiveScans(const ModelBase* model) : model_(model) { /* STUB */ }

        void append(std::shared_ptr<const VieVS::AbstractSource> const q, 
            Station& s, size_t t) noexcept;
        
        void updateScans(std::vector<Scan>& scans, size_t t);
    
    protected:
        std::vector<unsigned int> computeSlewTime(const ScanBuilder& scan, 
            const std::vector<Scan>& scans) noexcept;
        std::vector<unsigned int> computeEndOfLastScan(const ScanBuilder& scan, 
            const std::vector<Scan>& scans) noexcept;
    };
private:
    void loadScans(const std::vector<Scan>& scans);
    std::vector<Scan> readScans(void) const noexcept;
private:
    std::string dump(size_t t0, size_t tf) const noexcept;
private:
    // the sky coverage model used for the objective function
    std::map<ModelKey, GRBVar> var_;
    std::map<ModelKey, bool> sol_;
    std::map<ModelKey, bool> cov_;
    std::unordered_map<ModelKey, std::map<unsigned long, size_t>, ModelKey::Hash> snr_;
    std::map<unsigned long, size_t> sta2idx_;
    std::map<unsigned long, size_t> bln2idx_;
    std::map<unsigned long, size_t> src2idx_;
    std::vector<std::string> dumps_;
protected:
    // gurobi environment
    std::unique_ptr<GRBEnv> env_{nullptr};
    std::unique_ptr<GRBModel> model_{nullptr};
#endif // WITH_GUROBI
};
}
#endif // MODEL_BASE_H