/*
 *  VieSched++ Very Long Baseline Interferometry (VLBI) Scheduling Software
 *  Copyright (C) 2018  Matthias Schartner
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file Model.h
 * @brief class Model
 *
 * @author Hank Lewis
 * @date 22.01.2026
 */

#ifndef MODEL_BASE_H
#define MODEL_BASE_H

// system
#include <cassert>
#include <map>
#include <type_traits>

// gurobi
#ifdef WITH_GUROBI
#include <gurobi_c++.h>
#endif // WITH_GUROBI

// VieSchedpp
#include "Solution.h"
#include "../Source/SourceList.h"
#include "../Station/Network.h"
#include "../Scan/Scan.h"

namespace VieVS {
// forward declaration for ModelCoverage
class ModelBase; 

/**
 * @class ModelCoverage
 * @brief abstract struct modelling sky coverage
 * @author Hank Lewis
 * @date 24.05.2025
 */
struct ModelCoverage {
    virtual size_t cellCount(void) const noexcept = 0;
    virtual size_t calculateCell(const PointingVector& pv) const noexcept = 0;
};

/**
 * @class ModelCoverage13
 * @brief derivation of ModelCoverage with 13 discrete regions
 * @author Hank Lewis
 * @date 24.05.2025
 */
struct ModelCoverage13 : public ModelCoverage {
    size_t cellCount(void) const noexcept final;
    size_t calculateCell(const PointingVector& pv) const noexcept final;
};

/**
 * @class Model
 * @brief wraps ILP implementation
 * @author Hank Lewis
 * @date 24.05.2025
 */
class ModelBase {
    friend struct ModelCoverage;
    friend struct ModelCoverage13;

public:
    /**
     * @brief constructor
     * @author Hank Lewis
     *
     * @param network network
     * @param sourceList sourceList
     * @param sourceMask sourceMask
     * @param modes modes
     * @param blockLength blockLength
     * @param windowLength windowLength
     */
    ModelBase(VieVS::Network& network, VieVS::SourceList& sourceList, 
        const std::set<unsigned long>& sourceMask, 
        const std::shared_ptr<const ObservingMode>& modes,
        unsigned int blockLength, unsigned int windowLength);

    /**
     * @brief constructor with specified ModelCoverage implementation
     * @author Hank Lewis
     *
     * @param network network
     * @param sourceList sourceList
     * @param sourceMask sourceMask
     * @param modes modes
     * @param blockLength blockLength
     * @param windowLength windowLength
     */
    template<typename T>
    ModelBase(VieVS::Network& network, VieVS::SourceList& sourceList, 
        const std::set<unsigned long>& sourceMask, 
        const std::shared_ptr<const ObservingMode>& modes,
        unsigned int blockLength, unsigned int windowLength) : 
        ModelBase(network, sourceList, sourceMask, modes, blockLength, windowLength) {
            static_assert(std::is_base_of<ModelCoverage, T>::value, "unreachable");
            coverage_ = std::make_unique<T>();
        }

    /**
     * @brief destructor
     * @author Hank Lewis
    */
    ~ModelBase() = default;

    /**
     * @brief perform ILP optimization from scratch, without a starting point
     * @author Hank Lewis
     */
    bool optimize(void);

    /**
     * @brief perform ILP optimization using the greedy solution as a starting point
     * @author Hank Lewis
     *
     * @param scans the scans generated by Scheduler::start
     */
    std::vector<Scan> optimize(std::vector<Scan>& scans);

protected:
    /**
     * @struct Window
     * @brief stores the range of an optimization window
     * @author Hank Lewis
     * @date 24.05.2025
     */
    struct Window {
        size_t tp, tn; // the complete span, including prior and subsequent windows
        size_t t0, tf; // the actual optimization window
    };

    /**
     * @brief called after preparing the model (adding variables and loading warm start)
     * @author Hank Lewis
     *
     * @param window the optimization span
     */
    virtual void prepare(const Window& window) = 0;

#ifdef WITH_GUROBI
    /**
     * @brief returns a variable within the current optimization window
     * @author Hank Lewis
     *
     * @param key key
     */
    boost::optional<GRBVar> getVar(const Solution::Key& key) const noexcept;

    /**
     * @brief add a variable to the model
     * @author Hank Lewis
     *
     * @param key key
     * @param lb lb
     * @param ub ub
     * @param obj obj
     * @param vtype vtype
     */
    GRBVar& addVar(const Solution::Key& key, double lb, double ub, double obj, char vtype);

    /**
     * @brief for_each over all StaActive and BlnActive variables in a timespan
     * @author Hank Lewis
     *
     * @param t0 t0
     * @param tf tf
     * @param op a closure which accepts GRBVar&
     */
    template<typename F>
    void apply(size_t t0, size_t tf, F op) {
        for(size_t t : sol_.getBlocks(t0, tf)) {
            for(const auto q : sol_.getSources()) {
                for(const Station& s : sol_.getStations(t, q)) {
                    auto var = *getVar(Solution::Key::StaActive(&sol_, q, s, t));
                    op(var);
                }
            }
        }
        for(size_t t : sol_.getBlocks(t0, tf)) {
            for(const auto q : sol_.getSources()) {
                for(const Baseline& b : sol_.getBaselines(t, q)) {
                    auto var = *getVar(Solution::Key::BlnActive(&sol_, q, b, t));
                    op(var);
                }
            }
        }
    }

private:
    /**
     * @struct helper class for ActiveScans
     * @author Hank Lewis
     */
    struct ScanBuilder {
        unsigned long qId;
        std::map<unsigned long, std::pair<PointingVector, size_t>> sData;
        std::set<unsigned long> sContinuation;
        // none indicates failure, true is a successful append, 
        // false indicates that a new scan needs to be created and this one terminated
        boost::optional<bool> append(const ModelBase* model, 
            std::shared_ptr<const VieVS::AbstractSource> const q, 
            Station& s, size_t t) noexcept;
        Scan finish(const ModelBase* model, 
            const std::vector<unsigned int>& slewTime, 
            std::vector<unsigned int>& endOfLastScan) const noexcept;
    };

    /**
     * @class helper class for readScans
     * @author Hank Lewis
     */
    class ActiveScans {
    private:
        std::vector<ScanBuilder> scans_;
        std::vector<ScanBuilder> scansToAppend_;
        const ModelBase* model_;

    public:
        ActiveScans(const ModelBase* model) : model_(model) { /* STUB */ }
        void append(std::shared_ptr<const VieVS::AbstractSource> const q, 
            Station& s, size_t t) noexcept;
        void updateScans(std::vector<Scan>& scans, size_t t);
    
    protected:
        std::vector<unsigned int> computeSlewTime(const ScanBuilder& scan, 
            const std::vector<Scan>& scans) noexcept;
        std::vector<unsigned int> computeEndOfLastScan(const ScanBuilder& scan, 
            const std::vector<Scan>& scans) noexcept;
    };

    /**
     * @brief helper method for loadScans
     * @author Hank Lewis
     *
     * @param obs a preliminary set of observations from a single scan
     */
    std::set<std::tuple<const Observation*, size_t, size_t>> validateScan(const std::set<std::tuple<const Observation*, size_t, size_t>>& obs);
    
    /**
     * @brief helper method for loadScans
     * @author Hank Lewis
     *
     * @param scans scans from greedy solution
     */
    void loadScans(const std::vector<Scan>& scans);
    
    /**
     * @brief produces a series of VieVS::Scans from the Solution
     * @author Hank Lewis
     */
    std::vector<Scan> readScans(void) const noexcept;

    /**
     * @brief constructs a tabular view of the schedule where each source is keyed by a different character
     * @author Hank Lewis
     * 
     * @param t0 start of updated interval
     * @param tf end of updated interval
     */
    std::string dump(size_t t0, size_t tf) const noexcept;

private:
    // the sky coverage model used for the objective function
    std::map<Solution::Key, GRBVar> var_;
    // collection of outputs for printing at the end
    std::vector<std::string> dumps_;

protected:
    // solution map
    Solution sol_;
    // sky coverage model
    std::unique_ptr<ModelCoverage> coverage_;

protected:
    // gurobi environment
    std::unique_ptr<GRBEnv> env_{nullptr};
    std::unique_ptr<GRBModel> model_{nullptr};
#endif // WITH_GUROBI
};
}
#endif // MODEL_BASE_H