/*
 *  VieSched++ Very Long Baseline Interferometry (VLBI) Scheduling Software
 *  Copyright (C) 2018  Matthias Schartner
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file Model.h
 * @brief class Model
 *
 * @author Hank Lewis
 * @date 22.01.2026
 */

#ifndef MODEL_H
#define MODEL_H
#include <cassert>
#include <stdexcept>
#include <map>
#include <type_traits>

#ifdef WITH_GUROBI
#include <gurobi_c++.h>
#endif // WITH_GUROBI

#include "Source/SourceList.h"
#include "Station/Network.h"
#include "Scan/Scan.h"

namespace VieVS {
// forward declaration for ModelCoverage
class Model; 

/**
 * @class ModelCoverage
 * @brief abstract struct modelling sky coverage
 * @author Hank Lewis
 * @date 24.05.2025
 */
struct ModelCoverage {
    virtual size_t cellCount(void) const noexcept = 0;
    virtual size_t calculateCell(const Model* model, size_t t, 
        const std::shared_ptr<const AbstractSource> q, Station& s) const noexcept = 0;
};

struct ModelCoverage13 : ModelCoverage {
    size_t cellCount(void) const noexcept final;
    size_t calculateCell(const Model* model, size_t t, 
        const std::shared_ptr<const AbstractSource> q, Station& s) const noexcept final;
};

/**
 * @class Model
 * @brief wraps ILP implementation
 * @author Hank Lewis
 * @date 24.05.2025
 */
class Model {
    friend struct ModelCoverage;
    friend struct ModelCoverage13;
public:
    /**
     * @brief constructor
     * @author Hank Lewis
     *
     * @param network network
     * @param sourceList sourceList
     * @param blockLength blockLength
     */
    Model(VieVS::Network& network, VieVS::SourceList& sourceList, 
        unsigned int blockLength, unsigned int windowLength);

    /**
     * @brief constructor with specified ModelCoverage implementation
     * @author Hank Lewis
     *
     * @param network network
     * @param sourceList sourceList
     * @param blockLength blockLength
     */
    template<typename T>
    Model(VieVS::Network& network, VieVS::SourceList& sourceList, 
        unsigned int blockLength, unsigned int windowLength) : 
        Model(network, sourceList, blockLength, windowLength) {
            static_assert(std::is_base_of<ModelCoverage, T>::value, "unreachable");
            coverage_ = std::make_unique<T>();
        }

    /**
     * @brief destructor
     * @author Hank Lewis
    */
    ~Model() {
#ifdef WITH_GUROBI
        delete model_;
        delete env_;
#endif // WITH_GUROBI
    }

    /**
     * @brief perform ILP optimization from scratch, without a starting point
     * @author Hank Lewis
     */
    bool optimize(void);

    /**
     * @brief perform ILP optimization using the greedy solution as a starting point
     * @author Hank Lewis
     *
     * @param scans the scans generated by Scheduler::start
     */
    std::vector<Scan> optimize(std::vector<Scan>& scans);

private:
    bool checkStationVisibility(size_t t, 
        std::shared_ptr<const VieVS::AbstractSource> q, 
        Station& s) const noexcept;

    size_t calculateSlewTime(Station& s, 
        const std::shared_ptr<const AbstractSource> q1, 
        const std::shared_ptr<const AbstractSource> q2,
        size_t t1, size_t t2) const noexcept;

private:
    // references from VieVS::Scheduler
    VieVS::Network& network_;
    VieVS::SourceList& sourceList_;
    // number of segments in schedule
    size_t blockCount_;
    // the size of each time segment (in seconds)
    unsigned int blockLength_;
    // number of segments in the sliding optimization window
    size_t windowBlockCount_;
    // the length of the sliding optimization window (in seconds)
    unsigned int windowLength_;

private:
    // the sky coverage model used for the objective function
    std::unique_ptr<ModelCoverage> coverage_;

#ifdef WITH_GUROBI
private:
    /**
    * @class ModelKey
    * @brief key for accessing ILP variables
    * @author Hank Lewis
    * @date 03.03.2026
    */
    struct ModelKey {
        enum ModelKeyType {
            sta_active,
            bln_active,
            sta_coverage
        };
        ModelKeyType type;
        union {
            struct { size_t q, s, t; } sta_active;
            struct { size_t q, b, t; } bln_active;
            struct { size_t s, c; } sta_coverage;
        } key;

        bool operator<(const ModelKey& other) const;

        static ModelKey StaActive(const Model* model, 
            std::shared_ptr<const VieVS::AbstractSource> const q, 
            const Station& s, size_t t);

        static ModelKey BlnActive(const Model* model, 
            std::shared_ptr<const VieVS::AbstractSource> const q, 
            const Baseline& b, size_t t);

        static ModelKey StaCoverage(const Model* model, const Station& s, size_t c);
    };
private:
    boost::optional<GRBVar> getVar(const ModelKey& key) const noexcept;

    GRBVar& addVar(const ModelKey& key, double lb, double ub, double obj, char vtype);

private:
    struct ScanBuilder {
        unsigned long qId;
        std::map<unsigned long, std::pair<PointingVector, size_t>> sData;

        bool append(const Model* model, 
            std::shared_ptr<const VieVS::AbstractSource> const q, 
            Station& s, size_t t) noexcept;

        Scan finish(const Model* model, const std::vector<unsigned int>& slewTime) const noexcept;
    };

    class ActiveScans {
    public: // TODO: make private
        std::vector<ScanBuilder> scans_;
        const Model* model_;
    public:
        ActiveScans(const Model* model) : model_(model) { /* STUB */ }

        void append(std::shared_ptr<const VieVS::AbstractSource> const q, 
            Station& s, size_t t) noexcept;
        
        void updateScans(std::vector<Scan>& scans, size_t t);
    };

private:
    void loadScans(const std::vector<Scan>& scans);
    std::vector<Scan> readScans(void) const noexcept;

private:
    void dump(GRB_DoubleAttr attr) const noexcept;

private:
    std::map<ModelKey, GRBVar> var_;
    std::map<unsigned long, size_t> sta2idx_;
    std::map<unsigned long, size_t> bln2idx_;
    std::map<unsigned long, size_t> src2idx_;
private:
    // gurobi environment
    GRBEnv* env_ = nullptr;
    GRBModel* model_ = nullptr;
#endif // WITH_GUROBI
};
}
#endif // MODEL_H